// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/fs/fs.go
//
// Generated by this command:
//
//	mockgen -source=pkg/fs/fs.go -destination pkg/fs/mock/mockfs.go
//

// Package mock_fs is a generated GoMock package.
package mock_fs

import (
	fs0 "io/fs"
	reflect "reflect"

	fs "go.mws.cloud/util-toolset/pkg/internal/os/fs"
	gomock "go.uber.org/mock/gomock"
)

// MockFS is a mock of FS interface.
type MockFS struct {
	ctrl     *gomock.Controller
	recorder *MockFSMockRecorder
	isgomock struct{}
}

// MockFSMockRecorder is the mock recorder for MockFS.
type MockFSMockRecorder struct {
	mock *MockFS
}

// NewMockFS creates a new mock instance.
func NewMockFS(ctrl *gomock.Controller) *MockFS {
	mock := &MockFS{ctrl: ctrl}
	mock.recorder = &MockFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFS) EXPECT() *MockFSMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockFS) MkdirAll(path string, perm fs0.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockFSMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockFS)(nil).MkdirAll), path, perm)
}

// Open mocks base method.
func (m *MockFS) Open(name string) (fs0.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs0.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockFS)(nil).Open), name)
}

// OpenFile mocks base method.
func (m *MockFS) OpenFile(name string, flag int, perm fs0.FileMode) (fs.WritableFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", name, flag, perm)
	ret0, _ := ret[0].(fs.WritableFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockFSMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockFS)(nil).OpenFile), name, flag, perm)
}

// ReadDir mocks base method.
func (m *MockFS) ReadDir(name string) ([]fs0.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]fs0.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockFSMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockFS)(nil).ReadDir), name)
}

// Remove mocks base method.
func (m *MockFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockFS)(nil).Remove), name)
}

// RemoveAll mocks base method.
func (m *MockFS) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockFSMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockFS)(nil).RemoveAll), path)
}

// Rename mocks base method.
func (m *MockFS) Rename(src, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", src, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockFSMockRecorder) Rename(src, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockFS)(nil).Rename), src, dst)
}

// WriteFile mocks base method.
func (m *MockFS) WriteFile(name string, data []byte, perm fs0.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFS)(nil).WriteFile), name, data, perm)
}

// MockWriteOnlyFS is a mock of WriteOnlyFS interface.
type MockWriteOnlyFS struct {
	ctrl     *gomock.Controller
	recorder *MockWriteOnlyFSMockRecorder
	isgomock struct{}
}

// MockWriteOnlyFSMockRecorder is the mock recorder for MockWriteOnlyFS.
type MockWriteOnlyFSMockRecorder struct {
	mock *MockWriteOnlyFS
}

// NewMockWriteOnlyFS creates a new mock instance.
func NewMockWriteOnlyFS(ctrl *gomock.Controller) *MockWriteOnlyFS {
	mock := &MockWriteOnlyFS{ctrl: ctrl}
	mock.recorder = &MockWriteOnlyFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteOnlyFS) EXPECT() *MockWriteOnlyFSMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockWriteOnlyFS) MkdirAll(path string, perm fs0.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockWriteOnlyFSMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockWriteOnlyFS)(nil).MkdirAll), path, perm)
}

// OpenFile mocks base method.
func (m *MockWriteOnlyFS) OpenFile(name string, flag int, perm fs0.FileMode) (fs.WritableFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", name, flag, perm)
	ret0, _ := ret[0].(fs.WritableFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockWriteOnlyFSMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockWriteOnlyFS)(nil).OpenFile), name, flag, perm)
}

// Remove mocks base method.
func (m *MockWriteOnlyFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWriteOnlyFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWriteOnlyFS)(nil).Remove), name)
}

// RemoveAll mocks base method.
func (m *MockWriteOnlyFS) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockWriteOnlyFSMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockWriteOnlyFS)(nil).RemoveAll), path)
}

// Rename mocks base method.
func (m *MockWriteOnlyFS) Rename(src, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", src, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockWriteOnlyFSMockRecorder) Rename(src, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockWriteOnlyFS)(nil).Rename), src, dst)
}

// WriteFile mocks base method.
func (m *MockWriteOnlyFS) WriteFile(name string, data []byte, perm fs0.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockWriteOnlyFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockWriteOnlyFS)(nil).WriteFile), name, data, perm)
}

// MockListFS is a mock of ListFS interface.
type MockListFS struct {
	ctrl     *gomock.Controller
	recorder *MockListFSMockRecorder
	isgomock struct{}
}

// MockListFSMockRecorder is the mock recorder for MockListFS.
type MockListFSMockRecorder struct {
	mock *MockListFS
}

// NewMockListFS creates a new mock instance.
func NewMockListFS(ctrl *gomock.Controller) *MockListFS {
	mock := &MockListFS{ctrl: ctrl}
	mock.recorder = &MockListFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListFS) EXPECT() *MockListFSMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockListFS) List() ([]fs0.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]fs0.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListFSMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListFS)(nil).List))
}
